# Kitty terminal configuration

# Font
font_family      FiraCode Nerd Font
font_size        12.0

# Tab bar
tab_bar_style    powerline
tab_powerline_style slanted

# Window
window_padding_width 4
background_opacity 0.85
background_blur 20

# Performance
repaint_delay    10
input_delay      3
sync_to_monitor  yes

# Osaka Jade theme
foreground              #C1C497
background              #111C18
selection_foreground    #111C18
selection_background    #C1C497
cursor                  #D7C995
cursor_text_color       #000000
url_color               #2DD5B7
active_border_color     #71CEAD
inactive_border_color   #53685B
bell_border_color       #E5C736
active_tab_foreground   #111C18
active_tab_background   #C1C497
inactive_tab_foreground #C1C497
inactive_tab_background #111C18
tab_bar_background      #111C18

# ANSI colors
color0  #23372B
color1  #FF5345
color2  #549E6A
color3  #459451
color4  #509475
color5  #D2689C
color6  #2DD5B7
color7  #F6F5DD
color8  #53685B
color9  #DB9F9C
color10 #63b07a
color11 #E5C736
color12 #ACD4CF
color13 #75BBB3
color14 #8CD3CB
color15 #9EEBB3
